create extension if not exists "postgis" with schema "extensions";


  create table "public"."estates" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "address" text,
    "latitude" double precision,
    "longitude" double precision,
    "geom" extensions.geometry,
    "created_at" timestamp with time zone not null default now(),
    "rent_price" bigint,
    "fee_info" text,
    "geo_code" bigint,
    "img" text,
    "url" text,
    "floor_plan" text,
    "area" double precision,
    "years_old" integer,
    "floor_num" text
      );



  create table "public"."prefecture_train_lines" (
    "id" bigint generated by default as identity not null,
    "prefecture_code" bigint,
    "train_line_code" bigint,
    "created_at" timestamp with time zone not null default now()
      );



  create table "public"."prefectures" (
    "id" bigint generated by default as identity not null,
    "code" smallint,
    "name" character varying,
    "created_at" timestamp with time zone not null default now(),
    "latitude" double precision,
    "longitude" double precision,
    "zoom" smallint
      );



  create table "public"."stations" (
    "id" bigint generated by default as identity not null,
    "code" bigint,
    "name" character varying,
    "latitude" double precision,
    "longitude" double precision,
    "created_at" timestamp with time zone not null default now(),
    "prefecture_code" bigint,
    "line_code" bigint
      );



  create table "public"."train_lines" (
    "id" bigint generated by default as identity not null,
    "code" bigint,
    "name" character varying,
    "color" character varying,
    "latitude" double precision,
    "longitude" double precision,
    "zoom" smallint,
    "created_at" timestamp with time zone not null default now()
      );


CREATE INDEX idx_estates_geom ON public.estates USING gist (geom);

CREATE UNIQUE INDEX prefecture_train_lines_pkey ON public.prefecture_train_lines USING btree (id);

CREATE UNIQUE INDEX prefectures_code_key ON public.prefectures USING btree (code);

CREATE UNIQUE INDEX prefectures_pkey ON public.prefectures USING btree (id);

CREATE INDEX properties_geom_idx ON public.estates USING gist (geom);

CREATE UNIQUE INDEX properties_pkey ON public.estates USING btree (id);

CREATE UNIQUE INDEX tables_pkey ON public.stations USING btree (id);

CREATE UNIQUE INDEX train_lines_code_key ON public.train_lines USING btree (code);

CREATE UNIQUE INDEX train_lines_pkey ON public.train_lines USING btree (id);

alter table "public"."estates" add constraint "properties_pkey" PRIMARY KEY using index "properties_pkey";

alter table "public"."prefecture_train_lines" add constraint "prefecture_train_lines_pkey" PRIMARY KEY using index "prefecture_train_lines_pkey";

alter table "public"."prefectures" add constraint "prefectures_pkey" PRIMARY KEY using index "prefectures_pkey";

alter table "public"."stations" add constraint "tables_pkey" PRIMARY KEY using index "tables_pkey";

alter table "public"."train_lines" add constraint "train_lines_pkey" PRIMARY KEY using index "train_lines_pkey";

alter table "public"."prefecture_train_lines" add constraint "prefecture_train_lines_prefecture_code_fkey" FOREIGN KEY (prefecture_code) REFERENCES public.prefectures(code) not valid;

alter table "public"."prefecture_train_lines" validate constraint "prefecture_train_lines_prefecture_code_fkey";

alter table "public"."prefecture_train_lines" add constraint "prefecture_train_lines_train_line_code_fkey" FOREIGN KEY (train_line_code) REFERENCES public.train_lines(code) not valid;

alter table "public"."prefecture_train_lines" validate constraint "prefecture_train_lines_train_line_code_fkey";

alter table "public"."prefectures" add constraint "prefectures_code_key" UNIQUE using index "prefectures_code_key";

alter table "public"."stations" add constraint "stations_line_code_fkey" FOREIGN KEY (line_code) REFERENCES public.train_lines(code) not valid;

alter table "public"."stations" validate constraint "stations_line_code_fkey";

alter table "public"."stations" add constraint "stations_prefecture_code_fkey" FOREIGN KEY (prefecture_code) REFERENCES public.prefectures(code) not valid;

alter table "public"."stations" validate constraint "stations_prefecture_code_fkey";

alter table "public"."train_lines" add constraint "train_lines_code_key" UNIQUE using index "train_lines_code_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_estates_in_polygon(polygon_geojson text)
 RETURNS json
 LANGUAGE plpgsql
AS $function$DECLARE
  result JSON;
BEGIN
  SELECT json_agg(row_to_json(t))
  INTO result
  FROM (
    SELECT * FROM estates
    WHERE ST_Within(geom, ST_GeomFromGeoJSON(polygon_geojson))
  ) t;
  RETURN result;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_prefecture_line_relations(codes integer[])
 RETURNS TABLE(prefecture_code integer, line_code integer)
 LANGUAGE sql
AS $function$
  select distinct prefecture_code, line_code
  from stations
  where prefecture_code = any(codes);
$function$
;

CREATE OR REPLACE FUNCTION public.set_estates_geom()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  update estates
  set geom = ST_SetSRID(ST_Point(longitude, latitude), 4326)
  where latitude is not null and longitude is not null and geom is null;
$function$
;

grant delete on table "public"."estates" to "anon";

grant insert on table "public"."estates" to "anon";

grant references on table "public"."estates" to "anon";

grant select on table "public"."estates" to "anon";

grant trigger on table "public"."estates" to "anon";

grant truncate on table "public"."estates" to "anon";

grant update on table "public"."estates" to "anon";

grant delete on table "public"."estates" to "authenticated";

grant insert on table "public"."estates" to "authenticated";

grant references on table "public"."estates" to "authenticated";

grant select on table "public"."estates" to "authenticated";

grant trigger on table "public"."estates" to "authenticated";

grant truncate on table "public"."estates" to "authenticated";

grant update on table "public"."estates" to "authenticated";

grant delete on table "public"."estates" to "service_role";

grant insert on table "public"."estates" to "service_role";

grant references on table "public"."estates" to "service_role";

grant select on table "public"."estates" to "service_role";

grant trigger on table "public"."estates" to "service_role";

grant truncate on table "public"."estates" to "service_role";

grant update on table "public"."estates" to "service_role";

grant delete on table "public"."prefecture_train_lines" to "anon";

grant insert on table "public"."prefecture_train_lines" to "anon";

grant references on table "public"."prefecture_train_lines" to "anon";

grant select on table "public"."prefecture_train_lines" to "anon";

grant trigger on table "public"."prefecture_train_lines" to "anon";

grant truncate on table "public"."prefecture_train_lines" to "anon";

grant update on table "public"."prefecture_train_lines" to "anon";

grant delete on table "public"."prefecture_train_lines" to "authenticated";

grant insert on table "public"."prefecture_train_lines" to "authenticated";

grant references on table "public"."prefecture_train_lines" to "authenticated";

grant select on table "public"."prefecture_train_lines" to "authenticated";

grant trigger on table "public"."prefecture_train_lines" to "authenticated";

grant truncate on table "public"."prefecture_train_lines" to "authenticated";

grant update on table "public"."prefecture_train_lines" to "authenticated";

grant delete on table "public"."prefecture_train_lines" to "service_role";

grant insert on table "public"."prefecture_train_lines" to "service_role";

grant references on table "public"."prefecture_train_lines" to "service_role";

grant select on table "public"."prefecture_train_lines" to "service_role";

grant trigger on table "public"."prefecture_train_lines" to "service_role";

grant truncate on table "public"."prefecture_train_lines" to "service_role";

grant update on table "public"."prefecture_train_lines" to "service_role";

grant delete on table "public"."prefectures" to "anon";

grant insert on table "public"."prefectures" to "anon";

grant references on table "public"."prefectures" to "anon";

grant select on table "public"."prefectures" to "anon";

grant trigger on table "public"."prefectures" to "anon";

grant truncate on table "public"."prefectures" to "anon";

grant update on table "public"."prefectures" to "anon";

grant delete on table "public"."prefectures" to "authenticated";

grant insert on table "public"."prefectures" to "authenticated";

grant references on table "public"."prefectures" to "authenticated";

grant select on table "public"."prefectures" to "authenticated";

grant trigger on table "public"."prefectures" to "authenticated";

grant truncate on table "public"."prefectures" to "authenticated";

grant update on table "public"."prefectures" to "authenticated";

grant delete on table "public"."prefectures" to "service_role";

grant insert on table "public"."prefectures" to "service_role";

grant references on table "public"."prefectures" to "service_role";

grant select on table "public"."prefectures" to "service_role";

grant trigger on table "public"."prefectures" to "service_role";

grant truncate on table "public"."prefectures" to "service_role";

grant update on table "public"."prefectures" to "service_role";

grant delete on table "public"."stations" to "anon";

grant insert on table "public"."stations" to "anon";

grant references on table "public"."stations" to "anon";

grant select on table "public"."stations" to "anon";

grant trigger on table "public"."stations" to "anon";

grant truncate on table "public"."stations" to "anon";

grant update on table "public"."stations" to "anon";

grant delete on table "public"."stations" to "authenticated";

grant insert on table "public"."stations" to "authenticated";

grant references on table "public"."stations" to "authenticated";

grant select on table "public"."stations" to "authenticated";

grant trigger on table "public"."stations" to "authenticated";

grant truncate on table "public"."stations" to "authenticated";

grant update on table "public"."stations" to "authenticated";

grant delete on table "public"."stations" to "service_role";

grant insert on table "public"."stations" to "service_role";

grant references on table "public"."stations" to "service_role";

grant select on table "public"."stations" to "service_role";

grant trigger on table "public"."stations" to "service_role";

grant truncate on table "public"."stations" to "service_role";

grant update on table "public"."stations" to "service_role";

grant delete on table "public"."train_lines" to "anon";

grant insert on table "public"."train_lines" to "anon";

grant references on table "public"."train_lines" to "anon";

grant select on table "public"."train_lines" to "anon";

grant trigger on table "public"."train_lines" to "anon";

grant truncate on table "public"."train_lines" to "anon";

grant update on table "public"."train_lines" to "anon";

grant delete on table "public"."train_lines" to "authenticated";

grant insert on table "public"."train_lines" to "authenticated";

grant references on table "public"."train_lines" to "authenticated";

grant select on table "public"."train_lines" to "authenticated";

grant trigger on table "public"."train_lines" to "authenticated";

grant truncate on table "public"."train_lines" to "authenticated";

grant update on table "public"."train_lines" to "authenticated";

grant delete on table "public"."train_lines" to "service_role";

grant insert on table "public"."train_lines" to "service_role";

grant references on table "public"."train_lines" to "service_role";

grant select on table "public"."train_lines" to "service_role";

grant trigger on table "public"."train_lines" to "service_role";

grant truncate on table "public"."train_lines" to "service_role";

grant update on table "public"."train_lines" to "service_role";


